name: Integration Tests

on:
  push:
    branches:
      - '**'
  repository_dispatch:
    types: [run-cypress-tests] 

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      # --- PASO DE VALIDACIÓN ---
      - name: 🔍 Debug Xray Variables
        run: |
          echo "El ID de Test Execution es: ${{ github.event.client_payload.test_execution_key }}"
          echo "El Project Key es: SB"
      # ---------------------------

      - name: Install dependencies
        run: npm i

      - name: Install Cucumber Formatter (Linux)
        run: |
          curl -L https://github.com/cucumber/json-formatter/releases/download/v19.0.0/cucumber-json-formatter-linux-amd64 -o cucumber-json-formatter
          chmod +x cucumber-json-formatter

      - name: Cypress.io
        uses: cypress-io/github-action@v6.5.0
        with:
          command: npm run cypress:execution-tags
          browser: chrome
          record: true
        env:
          CUCUMBER_JSON_FORMATTER: ./cucumber-json-formatter
          
      - name: Import Results to Xray Test Plan
        run: |
          token=$(curl -H "Content-Type: application/json" -X POST --data "{ \"client_id\": \"${{ secrets.XRAY_CLIENT_ID }}\", \"client_secret\": \"${{ secrets.XRAY_CLIENT_SECRET }}\" }" https://xray.cloud.getxray.app/api/v2/authenticate | tr -d '"')

          curl -H "Content-Type: application/json" -X POST -H "Authorization: Bearer $token" \
          --data @cypress/reports/cucumber-results.json \
          "https://xray.cloud.getxray.app/api/v2/import/execution/cucumber?testPlanKey=${{ github.event.client_payload.test_plan_key }}"
          
      - name: Upload Cypress Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/**/*.mp4
