name: Regression Testing DemoQA

on:
  push:
    branches:
      - '**'
  # Agrega esta sección para recibir la señal de Jira
  repository_dispatch:
    types: [run-cypress-tests] 

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install dependencies
        run: npm i
      - name: Cypress.io
        uses: cypress-io/github-action@v6.5.0
        with:
          # Puedes usar el payload enviado por Jira para filtrar tags dinámicamente
          command: npm run cypress:execution-tags
          browser: chrome
          record: true
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.5
      - name: Upload Cypress Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/**/*.mp4